[project]
name = "htmlcssjs2"
version = "0.1.0"
description = "Add a short description here"
authors = ["Rahul Dave <rahuldave@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
python = ">=3.12.3,<3.13"
deno = ">=1.43.6,<1.44"
